### ISSUE TITLE
Update Piler 1.4.1

### ISSUE THREAD

**Issue by mac-linux-free** [simatec/piler-docker#1]
Hello,

could you please update to 1.4.1?

Thankyou :)

**Comment by simatec** [comment]
done ... can you test please?

**Comment by mac-linux-free** [comment]
I did docker-compose pull but no new image was pulled.

**Comment by mac-linux-free** [comment]
Then I updated the version number of the piler container and pulled and started but the config broke.
Is there an upgrade path?

Thank you.

**Comment by simatec** [comment]
you can simple Upgrade with compose.

`
docker-compose up --force-recreate --build -d
docker image prune -f
`

**Comment by mac-linux-free** [comment]
But after that the website is not comming up again. Luckily I had a snapshot of the VM. How could I upgrade just Piler in the container? I also made an custom Logo and stuff.

**Comment by simatec** [comment]
Please restore the snapshot and then perform the upgrade

**Comment by mac-linux-free** [comment]
I did it now. But still the old 1.3.12 build is starting. Should I do git pull or diff?

**Comment by simatec** [comment]
change the Version in docker-compose.yml

**Comment by mac-linux-free** [comment]
piler container is restarting ervery 4 seconds

**Comment by mac-linux-free** [comment]
can I do something or go back to my snapshot?

**Comment by simatec** [comment]
i will test it right away

**Comment by simatec** [comment]
1.4.1 have a Bug an i open a Issue on Piler

**Comment by mac-linux-free** [comment]
same error with 1.4.2

**Comment by simatec** [comment]
And 1.3.12 or 1.3.11?

**Comment by mac-linux-free** [comment]
1.3.12 runs because it is live

**Comment by mac-linux-free** [comment]
should i try a new setup?

**Comment by simatec** [comment]
I'll wait for the Mailpiler issue
https://bitbucket.org/jsuto/piler/issues/1259/docker-v141-not-running

**Comment by simatec** [comment]
The new Version from 1.4.2 is runnig.
Please Test it

**Comment by mac-linux-free** [comment]
Sadly not it is still restarting...is there a new version from 1.4.2 ?

**Comment by mac-linux-free** [comment]
also sutoj/piler:latest is failing like above

**Comment by mac-linux-free** [comment]
piler exited with code 1
piler exited with code 1
piler exited with code 1
piler exited with code 1
piler            | /usr/local/bin/start.sh: line 25: MYSQL_USERNAME: unbound variable
piler exited with code 1
piler exited with code 1
piler exited with code 1

**Comment by simatec** [comment]
Yes there is a new version.
Delete the old container first and pull to the new 1.4.2.

Unfortunately, the latest version of the piler is not up-to-date and should not be used.

**Comment by mac-linux-free** [comment]
But that is bad is my config and the data deleted also?

**Comment by simatec** [comment]
<img width="1259" alt="Bildschirmfoto 2022-12-16 um 23 03 27" src="https://user-images.githubusercontent.com/39792461/208197316-454cfede-6207-4de7-bdfa-8e6aab5fdc98.png">

**Comment by mac-linux-free** [comment]
hmm...dann probiere ich das mal

**Comment by mac-linux-free** [comment]
sed: can't read /etc/piler/manticore.conf: No such file or directory
sed: can't read /etc/piler/manticore.conf: No such file or directory
sed: can't read /etc/piler/manticore.conf: No such file or directory
sed: can't read /etc/piler/manticore.conf: No such file or directory
sed: can't read /etc/piler/manticore.conf: No such file or directory
sed: can't read /etc/piler/manticore.conf: No such file or directory
sed: can't read /etc/piler/manticore.conf: No such file or directory

immernoch gleicher fehler...auf einem neuen docker host ohne daten klappt es..nur das update nicht

**Comment by mac-linux-free** [comment]
klar könnte ich die neue maschine hochziehen und dann die alten daten exportieren und im neuen wieder importieren.

**Comment by mac-linux-free** [comment]
habe es gerade an einem 2ten piler probiert...genau der gleiche fehler....also heißt für mich das update mit daten ist nicht machbar

**Comment by simatec** [comment]
Ich werde dazu ein Issue bei Piler aufmachen.
Das Problem scheint ja beim Piler Container zu liegen.
Von welcher Version versuchst du auf 1.4.2 hochzuziehen?

**Comment by simatec** [comment]
https://bitbucket.org/jsuto/piler/issues/1261/docker-update-from-13x-not-possible

**Comment by mac-linux-free** [comment]
> Ich werde dazu ein Issue bei Piler aufmachen. Das Problem scheint ja beim Piler Container zu liegen. Von welcher Version versuchst du auf 1.4.2 hochzuziehen?

Danke Dir...von 1.3.12 das seit 1 Jahr läuft.

**Comment by simatec** [comment]
Zum besseren testen habe ich mal ein Updatemöglichkeit eingebaut.

https://github.com/simatec/piler-docker#update-guide

**Comment by simatec** [comment]
So wie ich jetzt die Info vom Entwickler habe, ist wohl ein reines Container Upgrade von 1.3.x auf 1.4.x nicht möglich.
Hier wurde Index von sphinx auf manticore umgestellt, was zu Problemen führt.

Man müsste also die 1.4.2 neu aufsetzen und die Daten importieren.
Hier wäre sicher sinnvoller gewesen einen Major Versionssprung zu machen und auch ein Hinweis darauf

**Comment by mac-linux-free** [comment]
ich bleibe erstmal bei 1.3.12....ist ja quasi produktiv...habe aber gesehen, das janos noch ein paar sachen geschrieben hat hat.

**Comment by simatec** [comment]
Ja ich versuche morgen mal ein paar Dinge noch in die Update bash einzubauen..
Heute mag ich kein Piler Server mehr aufsetzen

**Comment by simatec** [comment]
So ich habe jetzt nochmal ein wenig getestet. Mache mal bitte folgendes. Am besten aber vorher ein Snapshot oder Backup machen.

`cd /opt/piler-docker`
`docker-compose down`
`curl -OL https://raw.githubusercontent.com/simatec/piler-docker/main/update.sh`


Jetzt müssen 2 Volumes gelöscht werden. Solltest du dort etwas händisch geändert haben, dann sichere dir die vorher weg. Z.B. die piler.conf oder auch andere.

`docker volume rm piler-docker_piler_etc`
`docker volume rm piler-docker_piler_var`

Im Anschluss nun die update.sh ausführen

`bash update.sh`

Falls du jetzt noch deine händischen Anpassungen wieder zurückkopierst, musst du danach den Container nochmal starten.

`docker-compose restart piler`

**Comment by mac-linux-free** [comment]
Hey, danke für die ausführliche Anleitung...nur, wenn ich das var_Volume lösche, sind alle meine archivierten Mails weg.

**Comment by mac-linux-free** [comment]
Ich denke, die einzige Lösung ist Export und Import oder ich kann piler im container via src updaten.

**Comment by simatec** [comment]
Daum schrieb ich ja, alles vorher aus den Volumes sichern, was wichtig ist.
Kannst du mir mal deinen Inhalt vom var zeigen?
Problem ist, dass die 1.4.2 bei einem vorhandenen Volume die neuen benötigten Dateien nicht anlegt und auch alte Dateien, nicht aktualisiert

**Comment by mac-linux-free** [comment]
der Inhalt vom var ist der komplette Piler store...d.h. bei mir 80000 Dateien...danach muss ich doch sicher alles neu indizieren.

**Comment by simatec** [comment]
Ja indizieren musst du durch die Umstellung von Sphinx auf Manticore definitiv

**Comment by simatec** [comment]
Wie würdest du am sinnvollsten exportieren und importieren?

**Comment by mac-linux-free** [comment]
Wohl einfach im contaier pilerexport -A. Das Problem dabei ist, wenn jemand schon viele Daten/Mails hat wird durch den Export die Deduplizierung aufgehoben und das Export-Verzeichnis wächst auf der 3-4-8 fache. Bei mir jetzt kein Thema ich habe genug Storage, nur bei größeren Installationen könnte das ggf. zum Problem werden.
Jedenfalls ändere ich nichts mehr dieses Jahr...Danke Dir für Deine Mühen.

**Comment by simatec** [comment]
So habe mir das noch einmal angeschaut. 
Piler ist da leider in Version 1.4.2 nicht wirklich sinnvoll gebaut für Docker.
Wenn das Volume bereits existiert, zieht er sich da logischerweise die Daten.
Hier wird der nginx auf die Nase fallen, da sich in Verzeichnis www einiges geändert hat.

Als sprich ein Update von 1.3.x auf 1.4x muss zwingend die beiden Volumes neu erstellen.
Alles was wie z.B. der store ist, muss vorher gesichert werden.

Aktuell sehe ich da leider nur diesen weg oder halt ein pilerexport -A

**Comment by mac-linux-free** [comment]
Ok danke nochmal. pilerexport ind import ist nicht das Thema. Nur wenn ich z.b. schon viele User und Gruppen angelegt habe. Wie kann ich diese Daten behalten?

**Comment by simatec** [comment]
So ich habe jetzt eine Lösung gefunden. Diese hat bei mir so funktioniert und lief problemlos beim Update durch.
Hier mal die Befehle, die du gerne testen kannst.

`cd /opt/piler-docker`
`docker-compose down`

`curl -OL https://raw.githubusercontent.com/simatec/piler-docker/main/update.sh`

`rm -rf /var/lib/docker/volumes/piler-docker_piler_var/_data/www`
`mkdir -p /var/lib/docker/volumes/piler-docker_piler_var/_data/manticore`
`chown 1000:1000 /var/lib/docker/volumes/piler-docker_piler_var/_data/manticore`

`docker volume rm piler-docker_piler_etc`

`bash update.sh`

Falls du im etc Volume manuelle Anpassungen gemacht hast, musst du diese im Anschluss halt wieder einfügen.

**Comment by simatec** [comment]
Hast du mit Nginx installiert oder ohne?

**Comment by mac-linux-free** [comment]
Das war mein erster Gedanke... aber auch ohne kommt dieselbe Meldung.

**Comment by simatec** [comment]
Domain richtig eingetragen?

**Comment by mac-linux-free** [comment]
ja..selbst mit der IP klappt es ja nicht

**Comment by mac-linux-free** [comment]
War auch alles kein Thema mit der 1.3.12er Version

**Comment by simatec** [comment]
Ich hatte vor 2 Wochen zum Test ausgerollt und alles lief sauber mit der aktuellen Repo
Was sagt denn der Log, wenn du docker-compose up ausführst?

Gibt es Infos im Log?

**Comment by mac-linux-free** [comment]
habe jetzt noch im lxc container ipv6 deaktiviert..half nichts.

hier die logs

mysql_piler  | 2023-01-12 13:10:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.11+maria~ubu2004 started.
mysql_piler  | 2023-01-12 13:10:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_piler  | 2023-01-12 13:10:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.11+maria~ubu2004 started.
mysql_piler  | 2023-01-12 13:10:04+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
mysql_piler  | 2023-01-12 13:10:04 0 [Note] mariadbd (server 10.6.11-MariaDB-1:10.6.11+maria~ubu2004) starting as process 1 ...
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Using transactional memory
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Number of pools: 1
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mysql_piler  | 2023-01-12 13:10:04 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Using Linux native AIO
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: 128 rollback segments are active.
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: 10.6.11 started; log sequence number 272574; transaction id 390
mysql_piler  | 2023-01-12 13:10:04 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_piler  | 2023-01-12 13:10:04 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
mysql_piler  | 2023-01-12 13:10:04 0 [Note] Server socket created on IP: '0.0.0.0'.
mysql_piler  | 2023-01-12 13:10:04 0 [Note] Server socket created on IP: '::'.
mysql_piler  | 2023-01-12 13:10:04 0 [Note] InnoDB: Buffer pool(s) load completed at 230112 13:10:04
mysql_piler  | 2023-01-12 13:10:04 0 [Note] mariadbd: ready for connections.
mysql_piler  | Version: '10.6.11-MariaDB-1:10.6.11+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
piler        | ERROR 2002 (HY000): Can't connect to server on 'mysql' (115)
piler        | DEBUG: mysql is not ready
piler        | Database
piler        | information_schema
piler        | piler
piler        | DEBUG: mysql is ready
piler        | DEBUG: metadata table exists
piler        | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Permission denied.
piler        | rsyslogd: activation of module imklog failed [v8.2112.0 try https://www.rsyslog.com/e/2145 ]
piler        |  * Starting periodic command scheduler cron
piler        |    ...done.
piler        |  * Starting nginx nginx
piler        |    ...done.
piler        | starting searchd . . .
piler        | [Thu Jan 12 13:10:10.169 2023] [93] using config file '/etc/piler/manticore.conf' (10646 chars)...
piler        | Manticore 5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
piler        | starting daemon version '5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)' ...
piler        | listening on 127.0.0.1:9312 for sphinx and http(s)
piler        | listening on 127.0.0.1:9306 for mysql
piler        | Manticore 5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
piler        | precaching index 'main1'
piler        | precaching index 'main2'
piler        | precaching index 'main3'
piler        | precaching index 'main4'
piler        | precaching index 'dailydelta1'
piler        | precaching index 'delta1'
piler        | precaching index 'tag1'
piler        | precaching index 'note1'
piler        | Manticore 5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
piler        | starting piler-smtp . . . 
piler        | starting piler . . .

**Comment by simatec** [comment]
Schaue mal, ob das mysql Passwort Sonderzeichen hat

**Comment by mac-linux-free** [comment]
ja hat es...nicht gut?

**Comment by simatec** [comment]
Versuche nochmal alles zu löschen inkl. Volumes und Containern und dann mal ohne Sonderzeichen versuchen.
Da muss ich die Tage mal schauen, warum das mit Sonderzeichen nicht geht

**Comment by mac-linux-free** [comment]
leider nein...

`mysql_piler  | 2023-01-12 13:25:21+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.11+maria~ubu2004 started.
mysql_piler  | 2023-01-12 13:25:21+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_piler  | 2023-01-12 13:25:21+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.11+maria~ubu2004 started.
mysql_piler  | 2023-01-12 13:25:21+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
mysql_piler  | 2023-01-12 13:25:21 0 [Note] mariadbd (server 10.6.11-MariaDB-1:10.6.11+maria~ubu2004) starting as process 1 ...
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Using transactional memory
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Number of pools: 1
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mysql_piler  | 2023-01-12 13:25:21 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Using Linux native AIO
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: 128 rollback segments are active.
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: 10.6.11 started; log sequence number 272553; transaction id 390
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_piler  | 2023-01-12 13:25:21 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql_piler  | 2023-01-12 13:25:21 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
mysql_piler  | 2023-01-12 13:25:21 0 [Note] InnoDB: Buffer pool(s) load completed at 230112 13:25:21
mysql_piler  | 2023-01-12 13:25:21 0 [Note] Server socket created on IP: '0.0.0.0'.
mysql_piler  | 2023-01-12 13:25:21 0 [Note] Server socket created on IP: '::'.
mysql_piler  | 2023-01-12 13:25:21 0 [Note] mariadbd: ready for connections.
mysql_piler  | Version: '10.6.11-MariaDB-1:10.6.11+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
piler        | ERROR 2002 (HY000): Can't connect to server on 'mysql' (115)
piler        | DEBUG: mysql is not ready
piler        | Database
piler        | information_schema
piler        | piler
piler        | DEBUG: mysql is ready
piler        | DEBUG: metadata table exists
piler        | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Permission denied.
piler        | rsyslogd: activation of module imklog failed [v8.2112.0 try https://www.rsyslog.com/e/2145 ]
piler        |  * Starting periodic command scheduler cron
piler        |    ...done.
piler        |  * Starting nginx nginx
piler        |    ...done.
piler        | starting searchd . . .
piler        | [Thu Jan 12 13:25:26.788 2023] [91] using config file '/etc/piler/manticore.conf' (10645 chars)...
piler        | Manticore 5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
piler        | starting daemon version '5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)' ...
piler        | listening on 127.0.0.1:9312 for sphinx and http(s)
piler        | listening on 127.0.0.1:9306 for mysql
piler        | Manticore 5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
piler        | precaching index 'main1'
piler        | precaching index 'main2'
piler        | precaching index 'main3'
piler        | precaching index 'main4'
piler        | precaching index 'dailydelta1'
piler        | precaching index 'delta1'
piler        | precaching index 'tag1'
piler        | precaching index 'note1'
piler        | Manticore 5.0.2 348514c86@220530 dev (columnar 1.15.4 2fef34e@220522) (secondary 1.15.4 2fef34e@220522)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
piler        | starting piler-smtp . . . 
piler        | starting piler . . .
`

**Comment by mac-linux-free** [comment]
habe glaube den Fehler

  thrown in /etc/piler/auth-mailcow.php on line 47" while reading response header from upstream, client: 192.168.75.233, server: archiv.yyy.de, request: "POST /login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "archiv.wirtshausgarbe.de", referrer: "https://archiv.yyy.de/"
2023/01/12 13:32:13 [error] 65#65: *27 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/piler/auth-mailcow.php:47
Stack trace:
#0 /var/piler/www/model/user/auth.php(132): query_mailcow_for_email_access()
#1 /var/piler/www/model/user/auth.php(49): ModelUserAuth->checkFallbackLogin()
#2 /var/piler/www/controller/login/login.php(48): ModelUserAuth->checkLogin()
#3 /var/piler/www/system/front.php(36): ControllerLoginLogin->index()
#4 /var/piler/www/system/front.php(14): Front->execute()
#5 /var/piler/www/index.php(114): Front->dispatch()
#6 {main}

**Comment by simatec** [comment]
Müsste man sich die php mal anschauen, ob sich da etwas geändert hat
Kannst du die hier mal posten?

**Comment by mac-linux-free** [comment]
ok

<?php
/***
/usr/local/etc/piler/auth-mailcow.php
(C) 2021, Patrik Kernstock - patrik.kernstock.net.
GNU GPL3 License - No warranty. Use at own risk.

## REQUIREMENTS
- working mailpiler installation:
piler 1.3.9 (no domain wildcards supported, but working)
piler 1.3.10 (fully working, tested)
- working mailcow installation
- adjusting mailpiler configuration as below

## DESCRIPTION
After logging in with IMAP authentication, this can be used
to retrieve all alias email addresses, including wildcard,
the mailbox/username has access to, including the realname.

## USAGE
Add config settings to /usr/local/etc/piler/config-site.php:
```
$config['MAILCOW_API_KEY'] = 'YOUR_READONLY_API_KEY';
$config['MAILCOW_SET_REALNAME'] = true; // default = false
$config['CUSTOM_EMAIL_QUERY_FUNCTION'] = 'query_mailcow_for_email_access';
include('auth-mailcow.php');
```
*/

// query_mailcow_for_email_access($username) is a custom authentication
// function to overwrite the email addresses the user has access to.
function query_mailcow_for_email_access($username = '')
{
	global $config;
	$session = Registry::get('session');
	$data = $session->get("auth_data");

	// get emails where user has access to.
	$emails = mailcow_get_aliases($username);
	$wildcards = [];
	foreach ($emails as $i => $email) {
		// if email starts with "@", it's a domain wildcard alias
		if (substr($email, 0, 1) === '@') {
			$wildcards[$i] = substr($email, 1);
			unset($emails[$i]);
		}
	}
	$data['emails'] = array_merge($data['emails'] , $emails);

	// set realname, if available.
	if (isset($config['MAILCOW_SET_REALNAME'])
	&& $config['MAILCOW_SET_REALNAME'] === true) {
		// get the name from the mailcow API
		$realname = mailcow_get_mailbox_realname($username);
		if ($realname !== null) {
			$data['realname'] = $realname;
		}
	}

	// wildcard_domains support were implemented on 2020-10-31:
	// https://bitbucket.org/jsuto/piler/issues/1102
	// Released in piler 1.3.10.
	$session->set("wildcard_domains", $wildcards);
	$session->set("auth_data", $data);
}

// mailcow_get_aliases($mailbox) returns back the name of the
// mailbox user (specified in the mailbox details)
// Used to display this name on the top-right of mailpiler.
function mailcow_get_mailbox_realname($mailbox = '')
{
	// get mailbox info from mailcow instance
	$api = mailcow_query_api(sprintf('v1/get/mailbox/%s', $mailbox));
	if ($api !== null && !empty($api->name)) {
		return trim($api->name);
	}
	return null;
}

// mailcow_get_aliases($mailbox) returns back all aliases of
// given mailbox by querying the mailcow API.
function mailcow_get_aliases($mailbox = '')
{
	// get all aliases from mailcow instance
	$api = mailcow_query_api('v1/get/alias/all');
	if ($api !== null) {
		// valid data. yay!
		$emails = [];
		$mailbox = strtolower($mailbox);
		foreach ($api as $alias) {
			// check if alias is active (this is for newer instances)
			if (isset($alias->active_int) && $alias->active_int !== 1) {
				continue;
			}
			// check if alias is active (for older instances where active used)
			if (isset($alias->active) && $alias->active !== 1) {
				continue;
			}
			// if user email address is added to alias goto, allow access
			if (strpos(strtolower($alias->goto), $mailbox) !== false) {
				array_push($emails, strtolower($alias->address));
			}
		}
		return $emails;
	}

	// something went wrong.
	return [];
}

// mailcow_query_api($path) queries the mailcow API and returns
// back object with data or null when error occurred.
// In short: Basic API query function.
function mailcow_query_api($path)
{
	global $config;

	if (isset($config['MAILCOW_HOST'])) {
		$host = $config['MAILCOW_HOST'];
	} else {
		$host = $config['IMAP_HOST'];
	}

	// get data from mailcow instance
	$api = file_get_contents(
		sprintf('https://%s/api/%s', $host, $path),
		false, stream_context_create([
		'http' => [
			'method' => 'GET',
			'header' => [
				'Accept: application/json',
				sprintf('X-API-Key: %s', $config["MAILCOW_API_KEY"])
			],
			'timeout' => 5, // 5 secs timeout.
		]
	]));

	// decode json
	$api = json_decode($api);
	// check if we got valid json.
	if (json_last_error() === JSON_ERROR_NONE) {
		return $api;
	} else {
		return null;
	}
}

**Comment by mac-linux-free** [comment]
sonst mache ich es nochmal ohne mailcow integration

**Comment by mac-linux-free** [comment]
also ganz frisch ohne mailcow integration tut es.

**Comment by simatec** [comment]
Teste es gerade ... Was geht ist ein Login mit den Userdaten von Mailcow Mail Adressen

**Comment by mac-linux-free** [comment]
Dann gibt es bei der mailcow Integration keine lokalen Logins mehr?

**Comment by simatec** [comment]
Ich denke hier liegt mit der 1.4x ein Bug bei der Mailcow Integration vor. 
Hab mal Issues aufgemacht.
