### ISSUE TITLE
Sphinx Search support

### ISSUE THREAD

**Issue by almereyda** [simatec/piler-docker#10]
The installation instructions at https://gitlab.com/mailpiler/ubuntu-install#install-sphinx-search also use a full-text search index.

> "Sphinx is an open source full text search server that prioritizes efficiency, relevance (search quality), and integration ease."

How would this relate to this image here?

Does it appear useful to add it as well?

**Comment by simatec** [comment]
I don't really understand your issue

**Comment by almereyda** [comment]
I'm asking if Mailpiler has support of Sphinx Search, and if it would make sense to use it here.

**Comment by simatec** [comment]
Here is the full docu from Mailpiler is here
https://www.mailpiler.org/docs.html

**Comment by simatec** [comment]
This github project corresponds to the original Piler versions.
It's just made easy to set up and install with the installer here.

Therefore the original documentation of Mailpiler applies here completely.

I hope I could help you with this information

**Comment by almereyda** [comment]
I see, thank you. Mailpiler uses Manticore for search now.

* [Manticore Search](https://www.mailpiler.org/manticore-search/)
