### ISSUE TITLE
GitHub topic "mailpiler"

### ISSUE THREAD

**Issue by almereyda** [simatec/piler-docker#11]
There is a small GitHub topic growing around the term "mailpiler".

- https://github.com/topics/mailpiler

It could be nice to find this project as the most recently active Docker example there.

**Comment by simatec** [comment]
The Mailcow integration is already present in the install setup

**Comment by almereyda** [comment]
I don't understand what you are referring to. Which installation setup?

This issue was intended to be about the GitHub topic for mailpiler. What I forgot to state is to suggest to add the `mailpiler` topic to this repository in the top right of https://github.com/simatec/piler-docker, in so this container is more easy findable in the aforementioned list.

**Comment by simatec** [comment]
Sorry, I misunderstood your issue.
I adjusted the topics for this project and now it can also be found with the topic.

**Comment by almereyda** [comment]
Cool, thanks!

If you'd like to only use English terms, I would suggest to translate the German *archiv* and *mailarchiv* to **archive** and **mailarchive** (:
