### ISSUE TITLE
New docker compose version

### ISSUE THREAD

**Issue by netsrot303** [simatec/piler-docker#2]
Is ist possible to change the install-piler.sh to the newer docker compose version?
In my lxc Container the old docker-compose didn't work.
(bash: docker-compose: command not found)

**Comment by simatec** [comment]
What is different in the new docker-compose version?
Could not find any difference.

**Comment by netsrot303** [comment]
the call is made without hyphen.
example : docker compose up -d

**Comment by simatec** [comment]
Which version should this be, which is executed only without hyphen?

**Comment by netsrot303** [comment]
Das ist die Version wenn man über den Paketmanager das docker-compose-plugin installiert. (apt install docker-compose-plugin)
Das wird auch in den Mailcow docs so beschrieben.
https://docs.mailcow.email/i_u_m/i_u_m_install/#docker-and-docker-compose-installation

**Comment by IceFlom** [comment]
Genau, das alte docker-compose war in Python geschrieben und wird meines Wissens nicht mehr weiterentwickelt. Vor einiger Zeit wurde daraus ein offizielles Docker Plugin und ist damit direkt über apt installierbar. Der Aufruf ist damit statt `docker-compose` jetzt `docker compose`

**Comment by simatec** [comment]
done in v0.8.1
