### ISSUE TITLE
Restore from Emails not working

### ISSUE THREAD

**Issue by drh8ball** [simatec/piler-docker#4]
Hi, I installed your Piler Docker yesterday, great work, thank you very much for this.
Nearly everything is working as expected but the restore from an audit user.

I found a thread on bitbucket.

https://bitbucket.org/jsuto/piler/issues/1247/restore-to-mailbox-not-working-when-using

Can we add the option to switch to restore via smtp?

I created a user auditor@example.com in my ISPConfig, when I log in with this user in Piler, I can restore emails, from or to auditor@example.com.
After this, I added a user in Piler with email auditor@example.com and username auditor@example.com with the same password as in ISPConfig, with userrole auditor. 
From this point on, I am able to see all emails for the domain, but I am not able anymore to restore emails, even not my own.

When I try, I get this message from Dovecot:

`dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<auditor@example.com>, method=PLAIN, rip=192.168.11.3, lip=192.168.11.4, TLS, session=<XXXXXXXXXXXXXXX>`

P.s.: The real domain is not example.com!

Thank you for reading!

**Comment by drh8ball** [comment]
Ach, ich sehe gerade dass alle anderen Issues irgendwann in deutsch besprochen wurden. Wenn ich mich unverständlich ausgedrückt habe, kann ich es auch gerne noch mal in deutsch schildern.

**Comment by simatec** [comment]
Ich habe mir den Thread durchgelesen, bin aber noch nicht so recht schlau daraus geworden. 
was genau sollte hier mit integriert werden?

**Comment by drh8ball** [comment]
Ich vermute der der Switch restore over imap = 1 muss auf 0 gestellt werden? 
Das andere was die da schreiben, mit dem User, habe ich auch noch nicht so ganz verstanden.

**Comment by simatec** [comment]
Und wo findet man das in der Config? Mir ist da nix bekannt

**Comment by drh8ball** [comment]
in der piler.conf 
bei den imap daten

**Comment by simatec** [comment]
Hast du mal versucht, die Config anzupassen und den Container danach neuzustarten?
Funktioniert dann dein Vorhaben?

**Comment by drh8ball** [comment]
Kein vi und kein nano im Container ...

**Comment by simatec** [comment]
Die piler.conf liegt doch im volume. Dort kannst du sie bearbeiten

**Comment by simatec** [comment]
Konntest du de piler.conf editieren und testen?

**Comment by drh8ball** [comment]
Hallo, da bin ich wieder.
Bei mir wurde kein Volume angelegt.
`/opt/piler-docker# docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED       STATUS                PORTS                                                                                                         NAMES
0b87f113852d   simatec/piler:1.4.3                      "/start.sh"              4 days ago    Up 4 days (healthy)   0.0.0.0:25->25/tcp, :::25->25/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   piler
4307f27a7037   mariadb:10.6                             "docker-entrypoint.s…"   4 days ago    Up 4 days (healthy)   3306/tcp                                                                                                      mysql_piler
e56530f747f1   memcached:latest                         "docker-entrypoint.s…"   4 days ago    Up 4 days             11211/tcp                                                                                                     memcached_piler
`

**Comment by drh8ball** [comment]
Ok, jetzt habe ich das Volume entdeckt, und leider habe ich dir auch die falsche Datei genannt. Es ist die config-site.php.
Ich ändere das jetzt und starte mal neu.

**Comment by drh8ball** [comment]
Das Projekt wurde gerade auf der Arbeit gecanceled. Aber ja, die Einstellung in der config-site.php aus dem Volume hat genau das bewirkt. Also kann als gelöst markiert werden.
