### ISSUE TITLE
Kann Domain und User nicht löschen

### ISSUE THREAD

**Issue by DerKlausner** [simatec/piler-docker#8]
Ich habe jetzt mit der Installation rumgespielt und dabei Daten Domain und User angelegt die ich jetzt nicht mehr benötige.
Wenn ich die Domain löschen will gibt es ein Ungültige Daten, versuche ein User zu löschen gibt es ein Benutzerkennung ungültig.  In der Demo scheint das aber möglich zu sein. Gibt es noch eine Einstellung die ich übersehen haben?

**Comment by simatec** [comment]
Mailpiler ist sehr fixiert auf die Domain. Ich denke die bei der Installation angelegte Domain löschen wird dir nur Probleme bescheren
